<?php

namespace App\Service\TransactionValidators\CreditCards;

use App\Infrastructure\Interfaces\Repositories\AccountManagementRepositoryInterface;
use App\Repository\AccountManagementRepository;
use Illuminate\Validation\UnauthorizedException;

class CreditCardBelongUserValidation extends AbstractCreditCardValidator
{
    public function __construct(private int $userId, private string $creditCardNumber)
    {
    }

    public function validate(): bool
    {
        /* @var $accountManagementRepo AccountManagementRepository*/
        $accountManagementRepo = app(AccountManagementRepositoryInterface::class);

        if (!$accountManagementRepo->checkCreditCardBelongToUser($this->creditCardNumber, $this->userId)) {

            throw new UnauthorizedException();
        }

        return parent::validate(); // TODO: Change the autogenerated stub
    }
}
