<?php

namespace App\Service\TransactionValidators\CreditCards;

use App\Constants\TransactionConstants;
use App\Infrastructure\Interfaces\Repositories\AccountManagementRepositoryInterface;
use App\Repository\AccountManagementRepository;
use Illuminate\Validation\ValidationException;

class HasEnoughBalanceForTransactionValidation extends AbstractCreditCardValidator
{
    public function __construct(private string $creditCardNumber, private int $amount)
    {
    }

    public function validate(): bool
    {
        /* @var $accountManagementRepo AccountManagementRepository*/
        $accountManagementRepo = app(AccountManagementRepositoryInterface::class);

        $totalAmount = $this->amount + TransactionConstants::TRANSACTION_FEE;

        $hasEnoughBalance = $accountManagementRepo->hasEnoughBalanceInAccountCheckThroughCreditCard(
            $this->creditCardNumber,
            $totalAmount
        );

        if (!$hasEnoughBalance) {
            throw new ValidationException();
        }

        return parent::validate(); // TODO: Change the autogenerated stub
    }
}
